
apiVersion: v1
kind: Service
metadata:
  name: suspicious-events-detector-service
spec:
  selector:
    app: suspicious-events-detector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
